=== timothyarthur/AdArchive/3M/heresies_issue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="heresies_issue">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="issue_no" type="xs:int"/>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="pub_year" type="xs:gYear"> </xs:element>
                <xs:element name="pub_month" minOccurs="0" type="xs:gMonth"> </xs:element>
                <xs:element name="ad" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ad_creators">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string" minOccurs="0"/>
                                        <xs:element name="location" minOccurs="0"
                                            maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="address" type="xs:string"/>
                                                  <xs:element name="coordinates" type="xs:string"/>
                                                  <xs:element name="phone_number" type="xs:string"
                                                  minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="uri" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:anyURI"/>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="1" ref="about"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0"
                                ref="publication_advertised"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="features_list"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="topics_list"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="contents_list"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="copy"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="price"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="subscription_form"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="illustration"/>
                            <xs:element name="embedded_ad" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="about"/>
                                        <xs:element minOccurs="0" ref="publication_advertised"/>
                                        <xs:element minOccurs="0" ref="features_list"/>
                                        <xs:element minOccurs="0" ref="topics_list"/>
                                        <xs:element minOccurs="0" ref="contents_list"/>
                                        <xs:element minOccurs="0" ref="copy"/>
                                        <xs:element minOccurs="0" ref="price"/>
                                        <xs:element minOccurs="0" ref="subscription_form"/>
                                        <xs:element minOccurs="0" ref="illustration"/>
                                    </xs:sequence>
                                    <xs:attribute name="clipping_uri" type="xs:anyURI"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="clipping_uri" type="xs:anyURI"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="uri" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="about"/>
    <xs:element name="publication_advertised">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="title"> </xs:element>
                <xs:element maxOccurs="unbounded" ref="creator"> </xs:element>
                <xs:element name="type" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="about" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="no_pages" type="xs:int" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>For monographs</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="issuing_rule" minOccurs="0">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="no_issues" type="xs:int"/>
                            <xs:element name="time_span" type="xs:string"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="issue_advertised" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="text"/>
                                        <xs:element name="number" minOccurs="0" type="xs:string"/>
                                        <xs:element name="date" minOccurs="0">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="type"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="about" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="no_pages" minOccurs="0" type="xs:int"/>
                            <xs:element minOccurs="0" name="copy_deadline"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="article_advertised"
                                > </xs:element>
                        </xs:sequence>
                        <xs:attribute name="uri" type="xs:anyURI"/>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="article_advertised"> </xs:element>
                <xs:element minOccurs="0" name="date_founded" type="xs:gYear"/>
                <xs:element minOccurs="0" name="circulation" type="xs:int"/>
            </xs:sequence>
            <xs:attribute name="uri" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="features_list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="text" type="xs:string"/>
                <xs:element name="subject" type="xs:anyURI"/>
                <xs:element name="feature" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="topics_list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="text" type="xs:string"/>
                <xs:element name="subject" type="xs:anyURI"/>
                <xs:element name="topic" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="contents_list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="text" type="xs:string"/>
                <xs:element name="subject" type="xs:anyURI"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="article" type="xs:anyURI"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="author"/>
                <xs:element maxOccurs="unbounded" name="topic" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="copy">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="text" type="xs:string"/>
                <xs:element name="about" maxOccurs="unbounded"/>
                <xs:element name="author" minOccurs="0"/>
                <xs:element name="date" minOccurs="0" type="xs:string"/>
                <xs:element name="source" minOccurs="0"/>
                <xs:element name="type" minOccurs="0" maxOccurs="unbounded" type="xs:anyURI"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="price">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="subject" type="xs:anyURI"/>
                <xs:element name="value" type="xs:decimal"/>
                <xs:element name="currency" type="xs:string"/>
                <xs:element name="type" maxOccurs="unbounded" type="xs:anyURI"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="subscription_form">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="text" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="illustration">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="type"/>
                <xs:element name="about" maxOccurs="unbounded"/>
                <xs:element name="represents" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="clipping_uri" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="creator">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name"/>
                <xs:element name="role" minOccurs="0">
                    <xs:simpleType>
                        <xs:restriction base="xs:anyURI">
                            <xs:enumeration value="wikidata:Q482980"/>
                            <xs:enumeration value="wikidata:Q1607826"/>
                            <xs:enumeration value="wikidata:Q2516866"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="uri"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="title">
        <xs:complexType mixed="true">
            <xs:attribute name="type" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:anyURI">
                        <xs:enumeration value="bibo:shortTitle">
                            <xs:annotation>
                                <xs:documentation>Short form of a
                                                  title</xs:documentation>
                            </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="wikidata:Q1135389">
                            <xs:annotation>
                                <xs:documentation>Subtitle</xs:documentation>
                            </xs:annotation>
                        </xs:enumeration>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="article_advertised">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="title"> </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="creator"> </xs:element>
                <xs:element name="about" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="uri" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== timothyarthur/AdArchive/3M/issue_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<heresies_issue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/Users/tim/Documents/AdArchive/3M/heresies_issue.xsd">
    <issue_no>3</issue_no>
    <title>Lesbian art and artists</title>
    <pub_year>1977</pub_year><pub_month>--09</pub_month>
    <ad>
        <clipping_uri/>
        <ad_creators uri=""/>
        <about/><publication_advertised><title type="wikidata:Q1135389"/><creator/><issue_advertised><title><text/><date/></title><article_advertised><creator><name>Alice Austen</name></creator></article_advertised></issue_advertised></publication_advertised><illustration><clipping_uri/><type/><about/><represents/></illustration>
    </ad>
</heresies_issue>

=== timothyarthur/AdArchive/3M/full_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<heresies_issue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="heresies_issue.xsd" uri="sample:HERESIES_ISSUE_URI">
    <issue_no>HERESIES ISSUE NO</issue_no>
    <title>HERESIES ISSUE TITLE</title>
    <pub_year>HERESIES ISSUE YEAR</pub_year>
    <pub_month>HERESIES ISSUE MONTH</pub_month>
    <ad>
        <!--for all ads-->
        <!--ad_label>Heresies Issue [Issue no] [Main Subject] Ad</ad_label-->
        <clipping_uri>sample:AD_CLIPPING</clipping_uri>
        <ad_creators uri="sample:AD_CREATORS_URI">
            <name>AD CREATORS NAME</name>
            <location>
                <address>AD CREATORS ADDRESS</address>
                <coordinates>AD CREATORS COORDINATES</coordinates>
                <phone_number>AD CREATORS PHONE NUMBER</phone_number>
            </location>
        </ad_creators>
        
        <!--for subject information not included elsewhere-->
        <about>sample:AD_ABOUT</about>
        
        <!--for ads of publications-->
        <publication_advertised uri="sample:PUBLICATION_URI">
            <!-- Title types: bibo:shortTitle, wikidata:Q1135389 (subtitle) -->
            <title>PUBLICATION TITLE</title>
            <creator>
                <name>PUB CREATOR NAME</name>
                <role>sample:PUB_CREATOR_ROLE</role>
            </creator>
            <type>sample:PUB_TYPE</type>
            <about>sample:PUB_ABOUT</about>
            <no_pages>NUMBER OF PAGES</no_pages>
            
            <!--For serial publications-->
            <issuing_rule>
                <no_issues>NUMBER OF ISSUES</no_issues>
                <time_span>TIME SPAN</time_span>
            </issuing_rule>
            <issue_advertised uri="sample:ISSUE_URI">
                <title>ISSUE TITLE<number>ISSUE NUMBER</number>
                    <date>ISSUE DATE<type>ISSUE DATE TYPE</type>
                    </date>
                </title>
                <!--For articles specified as part of the given issue-->
                <article_advertised>
                    <title>ARTICLE TITLE</title>
                    <creators>
                        <creator>sample:ARTICLE_CREATOR</creator>
                        <role>sample:ARTICLE_CREATOR_ROLE</role>
                    </creators>
                    <about>sample:ARTICLE_ABOUT</about>
                </article_advertised>
            </issue_advertised>
            
            <!-- For articles not tied to a specific issue-->
            <article_advertised>
                <title>ARTICLE TITLE</title>
                <creators>
                    <creator>sample:ARTICLE_CREATOR</creator>
                    <role>sample:ARTICLE_CREATOR_ROLE</role>
                </creators>
                <about>sample:ARTICLE_ABOUT</about>
            </article_advertised>
            
        </publication_advertised>
        
        <!--Features and topics-->
        <features_list>
            <text>FEATURES LIST TEXT</text>
            <feature>sample:FEATURE</feature>
            <subject>sample:FEATURE_LIST_SUBJECT</subject>
        </features_list>
        
        <topics_list>
            <text>TOPIC LIST TEXT</text>
            <topic>sample:TOPIC</topic>
            <subject>sample:TOPIC_LIST_SUBJECT</subject>
        </topics_list>
        
        <!--ad copy-->
        <copy>
            <about>sample:COPY_ABOUT</about>
            <text>COPY TEXT</text>
            <author>COPY AUTHOR</author>
            <date>COPY DATE</date>
            <source>COPY SOURCE</source>
            <!--types: endorsement-->
            <type>COPY TYPE</type>
        </copy>
        
        <!--for ads with prices-->
        <ad_price>
            <price_subject>sample:PRICE_SUBJECT</price_subject>
            <price_value>PRICE VALUE</price_value>
            <price_currency>PRICE CURRENCY</price_currency>
            <type>sample:PRICE_TYPE</type>
        </ad_price>
        
        <!--For ads with illustrations-->
        <illustration>
            <about>ILLUSTRATION ABOUT</about>
            <represents>sample:ILLUSTRATION_REPRESENTS</represents>
            <clipping>sample:ILLUSTRATION_CLIPPING</clipping>
        </illustration>
        
        <!--For ads with embedded ads (usually ads for several monographs)-->
        <embedded_ad>
            <publication_advertised uri="sample:EMBEDDED_PUBLICATION_URI">
                <!-- Title types: bibo:shortTitle, wikidata:Q1135389 (subtitle) -->                
                <title>PUBLICATION TITLE 
                    <type>sample:PUB_TITLE_TYPE</type>
                </title>
                <type>sample:PUB_TYPE</type>
                <about>sample:PUB_ABOUT</about>
                <no_pages>NUMBER OF PAGES</no_pages>
                <creators>
                    <creator>sample:PUB_CREATOR</creator>
                    <!-- Example roles: wikidata:Q482980 (author), wikidata:Q1607826 (editor), 
                    wikidata:Q2516866 (publisher) -->
                    <role>sample:PUB_CREATOR_ROLE</role>
                </creators>
            </publication_advertised>
            
            <copy>
                <about>sample:COPY_ABOUT</about>
                <text>COPY TEXT</text>
                <author>COPY AUTHOR</author>
                <date>COPY DATE</date>
                <source>COPY SOURCE</source>
                <!--types: endorsement-->
                <type>COPY TYPE</type>
            </copy>
            
            <ad_price>
                <price_subject>sample:PRICE_SUBJECT</price_subject>
                <price_value>PRICE VALUE</price_value>
                <price_currency>PRICE CURRENCY</price_currency>
                <type>sample:PRICE_TYPE</type>
            </ad_price>
            
        </embedded_ad>
    </ad>
</heresies_issue>
