=== timothyarthur/AdArchive/XML:3M/adarchive_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="heresies_issue">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="issue_title"/>
                <xs:element name="ad" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ad_creators">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string" minOccurs="0"/>
                                        <xs:element name="location" minOccurs="0"
                                            maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="address" type="xs:string"
                                                  minOccurs="0"/>
                                                  <xs:element name="coordinates" type="xs:string"
                                                  minOccurs="0"/>
                                                  <xs:element name="phone_number" type="xs:string"
                                                  minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute use="required" ref="uri"> </xs:attribute>
                                    <xs:attribute name="role"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="1" ref="about"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0"
                                ref="publication_advertised"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="features_list"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="topics_list"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="contents_list"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="copy"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="price"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="subscription_form"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="illustration"/>
                            <xs:element name="embedded_ad" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="about"/>
                                        <xs:element minOccurs="0" ref="publication_advertised"/>
                                        <xs:element minOccurs="0" ref="features_list"/>
                                        <xs:element minOccurs="0" ref="topics_list"/>
                                        <xs:element minOccurs="0" ref="contents_list"/>
                                        <xs:element minOccurs="0" ref="copy"/>
                                        <xs:element minOccurs="0" ref="price"/>
                                        <xs:element minOccurs="0" ref="subscription_form"/>
                                        <xs:element minOccurs="0" ref="illustration"/>
                                    </xs:sequence>
                                    <xs:attribute ref="clipping_uri"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute ref="clipping_uri"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="uri"/>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="clipping_uri" type="xs:anyURI"/>
    <xs:attribute name="uri" type="xs:anyURI"/>
    <xs:element name="about">
        <xs:complexType mixed="true">
            <xs:attribute ref="uri"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="publication_advertised">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="title"> </xs:element>
                <xs:element maxOccurs="unbounded" ref="creator"> </xs:element>
                <xs:element name="publication_type" type="xs:anyURI" minOccurs="0"
                    maxOccurs="unbounded"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="about"/>
                <xs:element minOccurs="0" ref="no_pages"> </xs:element>
                <xs:element name="issuing_rule" minOccurs="0">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="no_issues" type="xs:int"/>
                            <xs:element name="time_span" type="xs:string"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="issue_advertised" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="issue_title"> </xs:element>
                            <xs:element minOccurs="0" maxOccurs="unbounded" ref="about"/>
                            <xs:element minOccurs="0" ref="no_pages"/>
                            <xs:element minOccurs="0" name="copy_deadline"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="article_advertised"
                                > </xs:element>
                        </xs:sequence>
                        <xs:attribute ref="uri"/>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="article_advertised"> </xs:element>
                <xs:element minOccurs="0" name="date_founded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="circulation" type="xs:int"/>
            </xs:sequence>
            <xs:attribute ref="uri"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="features_list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="text"/>
                <xs:element ref="subject"/>
                <xs:element name="feature" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:attribute ref="uri"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="topics_list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="text"/>
                <xs:element ref="subject"/>
                <xs:element maxOccurs="unbounded" ref="topic"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="contents_list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="text"/>
                <xs:element ref="subject"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="article_advertised"> </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="author"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="topic"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="publication_advertised"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="copy">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="text"/>
                <xs:element maxOccurs="unbounded" ref="about"/>
                <xs:element minOccurs="0" ref="author"/>
                <xs:element minOccurs="0" ref="date"/>
                <xs:element name="source" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="uri"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="copy_type" minOccurs="0" maxOccurs="unbounded" type="xs:anyURI"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="price">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="subject" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:anyURI">
                                <xs:attribute ref="uri"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="value" type="xs:decimal"/>
                <xs:element name="currency" type="xs:string"/>
                <xs:element name="type" maxOccurs="unbounded" type="xs:anyURI"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="subscription_form">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="text" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="illustration">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="type"/>
                <xs:element name="about" maxOccurs="unbounded"/>
                <xs:element name="represents" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="clipping_uri" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="creator">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" maxOccurs="unbounded"/>
                <xs:element name="role" minOccurs="0">
                    <xs:simpleType>
                        <xs:restriction base="xs:anyURI">
                            <xs:enumeration value="wikidata:Q482980"/>
                            <xs:enumeration value="wikidata:Q1607826"/>
                            <xs:enumeration value="wikidata:Q2516866"/>
                            <xs:enumeration value="wikidata:P170"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="uri"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="title">
        <xs:complexType mixed="true">
            <xs:attribute name="type" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:anyURI">
                        <xs:enumeration value="bibo:shortTitle">
                            <xs:annotation>
                                <xs:documentation>Short form of a
                                                  title</xs:documentation>
                            </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="wikidata:Q1135389">
                            <xs:annotation>
                                <xs:documentation>Subtitle</xs:documentation>
                            </xs:annotation>
                        </xs:enumeration>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="issue_title">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element name="number" minOccurs="0" type="xs:string"/>
                <xs:element minOccurs="0" ref="date"> </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="article_advertised">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="title"> </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="creator"> </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="about"/>
            </xs:sequence>
            <xs:attribute ref="uri"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="topic">
        <xs:complexType mixed="true">
            <xs:attribute ref="uri"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="subject">
        <xs:complexType mixed="true">
            <xs:attribute ref="uri"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="author">
        <xs:complexType mixed="true">
            <xs:attribute ref="uri"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="no_pages" type="xs:int"> </xs:element>
    <xs:element name="text" type="xs:string"/>
    <xs:element name="date">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="type"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== timothyarthur/AdArchive/XML:3M/issues/issue_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<heresies_issue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="adarchive_schema.xsd">
    <issue_title>
        <title>Lesbian Art and Artists</title>
        <number>3</number>
        <date>1977-09</date>
    </issue_title>
  <ad clipping_uri="https://iiif.archivelab.org/iiif/heresies_03$117/138,2475,1111,648/full/0/default.jpg">

        <ad_creators uri="JUMP_CUT_CREATORS"/>
        <about>Contemporary Cinema</about>
        <publication_advertised uri="wikidata:Q319608">
            <title>Jump Cut</title>
            <creator uri="JUMP_CUT_CREATORS">
                <name>Jump Cut creators</name>
                <role>wikidata:P170</role>
            </creator>
            <publication_type>periodical</publication_type>
            <publication_type>scholarly journal</publication_type>
            <about>social context of cinema</about>
            <about>political context of cinema</about>
            <about>contemporary cinema</about>
            <about>radical film criticism</about>
            <issuing_rule>
                <no_issues>6</no_issues>
                <time_span>yearly</time_span>
            </issuing_rule>
        </publication_advertised>
        <copy>
            <text>examining cinema in its social and political context</text>
            <about>social context of cinema</about>
            <about>political context of cinema</about>
        </copy>
        <copy>
            <text>providing in-depth analyses of current films</text>
            <about>film analysis</about><about>current films</about><about>contemporary cinema</about>
        </copy><copy><text>developing a radical film criticism</text><about>radical film criticism</about></copy>
        <price>
            <subject>wikidata:Q319608</subject>
            <value>3</value>
            <currency>USD</currency>
            <type>subscription</type>
            <type>yearly</type>
        </price>
    </ad>
    <ad clipping_uri="https://iiif.archivelab.org/iiif/heresies_03$117/248,1627,778,823/full/0/default.jpg">

        <ad_creators uri="DYKE_CREATORS">
            <name>DYKE creators</name>
        </ad_creators>
        <about>Lesbian Culture</about>
        <publication_advertised>
            <title>DYKE</title>
            <title type="wikidata:Q1135389">A QUARTERLY</title>
            <creator uri="DYKE_CREATORS">
                <name>Dyke creators</name>
                <role>wikidata:P170</role>
            </creator>
            <issue_advertised>
                <issue_title>
                    <title>Fall '76</title>
                    <date>Fall 1976</date>
                </issue_title>

                <about>analysis</about>
                <!--add remaining abouts-->
                <article_advertised>
                    <title>Making a Backpack</title>
                    <about>Making a Backpack</about>
                </article_advertised>
                <article_advertised>
                    <title>Mouth Care</title>
                    <about>Oral Care</about>
                </article_advertised>
                <article_advertised>
                    <title>Photos by Alice Austen</title>
                    <creator uri="wikidata:Q538225">
                        <name>Alice Austen</name>
                    </creator>
                    <about>Photography</about>
                </article_advertised>
                <article_advertised>
                    <title>Name Change</title>
                    <about>Name Change</about>
                </article_advertised>
                <article_advertised>
                    <title>Coming Out On Celluloid</title>
                    <about>Film</about>
                    <about>Coming Out</about>
                </article_advertised>
                <article_advertised>
                    <title>Giving Up Kidz</title>
                    <about>Giving Up Kidz</about>
                </article_advertised>
            </issue_advertised>
            <issue_advertised>
                <issue_title>
                    <title>Winter '76-'77</title>
                </issue_title>
            </issue_advertised>

            <issue_advertised>
                <issue_title>
                    <title>Spring '77 Ethnic Dykes</title>
                    <date>Spring 1977</date><!--Rewrote from "Spring '77"-->
                </issue_title>
                <about>Ethnic Dykes</about><copy_deadline>1977-02-01</copy_deadline><!--Added copy deadline-->
            </issue_advertised>
            <issue_advertised>
                <issue_title>
                    <title>Spring '77 Animals</title>
                    <date>Spring '77</date>
                </issue_title>
                <about>Animals</about><copy_deadline>1977-05-01</copy_deadline><!--Added copy deadline-->
            </issue_advertised>
        </publication_advertised>
        <copy>
            <text>SUBSCRIBE!</text>
            <about>Subscription</about>
        </copy>
        <copy>
            <text>We are looking for graphic and written contributions. We pay for all work that we print. Write for details.</text>
            <about>Contributions</about>
            <author uri="DYKE_CREATORS"/>
        </copy>
        <price>
            <subject>DYKE</subject>
            <value>8</value>
            <currency>USD</currency>
            <type>yearly</type>
        </price>
        <price>
            <subject>DYKE</subject>
            <value>2.75</value>
            <currency>USD</currency>
            <type>Sample copy</type>
        </price>
        <illustration clipping_uri="https://iiif.archivelab.org/iiif/heresies_03$117/248,1627,778,823/full/0/default.jpg">
            <type>logo</type>
            <type>illustration</type>
            <about>DYKE</about>
        </illustration>
    </ad>
    <ad clipping_uri="https://iiif.archivelab.org/iiif/heresies_03$117/155,138,971,1458/full/0/default.jpg">

        <ad_creators uri="SINISTER_WISDOM_CREATORS">
            <name>Siniser Wisdom creators</name>
        </ad_creators>
        <about>Lesbian Culture</about>
        <publication_advertised uri="wikidata:Q7524444">
            <title>Sinister Wisdom</title>
            <creator uri="SINISTER_WISDOM_CREATORS">
                <name>Sinister Wisdom</name>
                <role>wikidata:P170</role>
            </creator>
            <about>Lesbian culture</about>
        </publication_advertised>
        <copy>
            <text>A journal of words and pictures for the lesbian imagination in all women</text>
            <about>Lesbian culture</about>
            <about>Lesbian imagination</about>
        </copy>
        <copy>
            <text>"...a substantial, serious effort to explore all aspects of the lesbian's world. There are special issues such as "Lesbian Writing and Publishing," which give in-depth coverage of the subject... The politics, psychology, aesthetics, etc. of the movement is examined... by good to excellent writers. … A major contribution, and recommended."</text>
            <about uri="wikidata:Q7524444"/><!--moved URI to @uri attribute and added "wikidata:" prefix-->
            <author>Library Journal</author>
            <copy_type>review</copy_type>
        </copy>
        <copy>
            <text>"… a heady brew of writing, conversing, questioning, and sharing between writers who have a special commitment to the emotional and physical truths of lesbianism. Intelligence and passion abound... the whole is open-ended and very alive. </text>
            <about uri="wikidata: Q7524444"/><!--moved URI to @uri attribute and added "wikidata:" prefix-->
            <author>The Spokeswoman</author>
            <copy_type>review</copy_type>
        </copy>
        <copy>
            <text>"… the hippest DYKE document(s) we've seen in so long..."</text>
            <about uri="wikidata:Q7524444"/><!--moved URI to @uri attribute and added "wikidata:" prefix-->
            <author>C.L.I.J.</author>
            <!--uncertain on initials-->
            <copy_type>review</copy_type>
        </copy>
        <copy>
            <text>SUBSCRIBE</text>
            <about>subscription</about>
            <copy_type>subscription</copy_type>
        </copy>
        <copy>
            <text>(All copies mailed in plain brown wrapper.)</text>
            <about>mailing copy</about><about>concealment</about>
        </copy>
        <price>
            <subject uri="wikidata:Q7524444">Sinister Wisdom</subject><!--changed schema to accept URI as attribute for subject and added subject name-->
            <value>4.50</value>
            <currency>USD</currency>
            <type>yearly</type>
        </price>
        <price>
            <subject uri="wikidata:Q7524444">Sinister Wisdom</subject>
            <value>9.00</value>
            <currency>USD</currency>
            <type>biyearly</type>
        </price>
        <illustration clipping_uri="https://iiif.archivelab.org/iiif/heresies_03$117/210,1134,392,402/full/0/default.jpg">
            <type>illustration</type>
            <type>logo</type>
            <about>Sinister Wisdom</about>
            <represents>https://sparql.cwrc.ca/ontologies/cwrc.html#woman</represents>
            <represents>seated figure</represents>
            <represents>bird</represents>
        </illustration>
    </ad>
    <ad clipping_uri="https://iiif.archivelab.org/iiif/heresies_03$118/1117,866,1104,1200/full/0/default.jpg">

        <ad_creators uri="THE_FEMINIST_ART_JOURNAL">
            <name>The Feminist Art Journal creators</name>
        </ad_creators>
        <about>Feminist art</about>
        <publication_advertised uri="wikidata:Q18207079">
            <title>The Feminist Art Journal</title>
            <creator uri="THE_FEMINIST_ART_JOURNAL_CREATORS">
                <name>The Feminist Art Journal creators</name>
